# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Winthrop Gillis
email: win.gillis@gmail.com
description: Winthrop Gillis - travelling through space for the right ideas
baseurl: / # the subpath of your site, e.g. /blog
url: https://wingillis.github.io # the base hostname & protocol for your site, e.g. http://example.com

paginate: 20
paginate_path: "blog/page:num/"
permalink: /blog/:title/

twitter_username: DubGill
github_username:  wingillis
rss_enabled: true
# ga_analytics: UA-74958647-1 # Add your GA Tracking Id
discus_identifier: wingillis # Add your Disqus identifier

assets:
  compress:
    css: true
    js: true
  sources:
    - _assets/stylesheets
    - _assets/images
    - _assets/scripts
# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
  - processors/
